learning_users/basic_app/urls.py
from django.contrib import admin
from django.urls import path
from basic_app import views

app_name = 'basic_app'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_login/', views.user_login, name='user_login')
]

learning_users/learning_users/urls.py
from django.contrib import admin
from django.urls import path, include
from basic_app import views
urlpatterns = [
    path('', views.index, name='index'),
    path('admin/', admin.site.urls),
    path('basic_app/', include('basic_app.urls')),
    path('logout/', views.user_logout, name='logout'),
    path('special/', views.special, name = 'special')
]

learning_users/basic_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    #additonals
    portfolio_site = models.URLField(blank=True)

    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__(self):
        return self.user.username

learning_users/basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta():
        model = User
        fields = ('username', 'email', 'password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site', 'profile_pic')

learning_users/basic_app/views.py
from django.shortcuts import render
from basic_app.forms import UserProfileInfoForm, UserForm

from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    return render(request, 'basic_app/index.html')

@login_required
def special(request):
    return render(request, 'basic_app/special.html')

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

def register(request):

    registered = False

    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        user_profile = UserProfileInfoForm(data=request.POST)


        if user_form.is_valid() and user_profile.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = user_profile.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES['profile_pic']

            profile.save()

            registered = True

        else:
            print(user_form.errors, user_profile.errors)

    else:
        user_form = UserForm()
        user_profile = UserProfileInfoForm()


    return render(request, 'basic_app/registration.html', {'user_form':user_form,
                                                            'user_profile':user_profile,
                                                            'registered':registered})

def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username = username, password = password)
        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("User not active")
        else:
            print('Someone tried to login with username {} and password {}'.format(username, password))
            return HttpResponse('Invalid username/password')
    else:
        return render(request, 'basic_app/login.html', {})

learning_users/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">HOME</a>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link" aria-current="page" href="{% url 'admin:index'%}">Admin</a>
            <a class="nav-link" href="{% url 'basic_app:register' %}">Sign UP</a>

            {% if user.is_authenticated %}
            <a class="nav-link" href="{% url 'special' %}">special</a>
            <a class="nav-link" aria-current="page" href="{% url 'logout' %}">Logout</a>
            {% else %}
            <a class="nav-link" aria-current="page" href="{% url 'basic_app:user_login' %}">Login</a>
            {% endif %}

          </div>
        </div>
      </div>
    </nav>

    <div class="container">
      {% block body_block %}
      {% endblock %}
    </div>
  </body>
</html>

learning_users/templates/basic_app/index.html
{% extends 'basic_app/base.html '%}
  {% block body_block %}

  <div class="jumbotron">
    <h1>Wellcome to Django level five</h1>
  </div>

  {% endblock %}

learning_users/templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% block body_block %}

<div class="jumbotron">
  <h2>Please login: </h2>

  <form action="{% url 'basic_app:user_login' %}" method="post">
    {% csrf_token %}
    <label for="username">Username:</label>
    <input type="text" name="username" placeholder="Enter username">
    <label for="password">Password:</label>
    <input type="password" name="password">
    <input type="submit" value="Logn">
  </form>
</div>
{% endblock %}

learning_users/templates/basic_app/registration.html
{% extends 'basic_app/base.html '%}
{% load static %}
  {% block body_block %}

  <div class="jumbotron">
    {% if registered %}
      <h1>Thankk you for registering</h1>
    {% else %}
      <h1>Please fill out the form:</h1>
      <form enctype="multipart/form-data" method="POST">
        {% csrf_token %}
        {{ user_form.as_p }}
        {{ user_profile.as_p }}
        <input type="submit" name="" class="btn btn-secondary" value="Register">
      </form>
    {% endif %}
  </div>
  {% endblock %}

learning_users/templates/basic_app/special.html
{% extends 'basic_app/base.html' %}

{% block body_block %}
<div class="jumbotron">
  <h1>You are a special user! </h1>
</div>
{% endblock %}